# Generated by Django 6.0.7 on 2026-08-09 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('favicon', models.FileField(upload_to='static/uploads')),
                ('logo', models.FileField(upload_to='static/uploads')),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator, django.core.validators.MaxLengthValidator(14)])),
                ('address', models.CharField(max_length=100)),
                ('fb_link', models.URLField(blank=True)),
                ('insta_link', models.URLField(blank=True)),
            ],
        ),
    ]
